version: '3'

services:
  database:
    image: postgres:14
    volumes:
      - vol_qe_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quadratic_equation_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin"]
      interval: 3s
      timeout: 3s
      retries: 3
    restart: always

  backend:
    image: imoskalenkoxvx/quadratic-equation:latest
    environment:
      PS_DB: quadratic_equation_db
      PS_USER: admin
      PS_PASSWORD: admin
      PS_HOST: database
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      database:
        condition: service_healthy
    restart: always
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

volumes:
  vol_qe_db:
