server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:6666/test_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    defer-datasource-initialization: true
    database: postgresql
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



logging:
  file:
    name: logger.log
  level:
    org:
      springframework: INFO
