server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://${PS_HOST}:5432/${PS_DB}   #PS_DB=test_db
    driver-class-name: org.postgresql.Driver
    username: ${PS_USER}                               #PS_USER=admin
    password: ${PS_PASSWORD}                           #PS_PASSWORD=admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    defer-datasource-initialization: true
    database: postgresql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



logging:
  file:
    name: logger.log
  level:
    org:
      springframework: INFO
